In [1]:
import os
os.chdir("../..")
from itertools import product
import json
import matplotlib.pyplot as plt
import pandas as pd
import requests
# !pip install google-api-python-client
from googleapiclient.discovery import build

# local import
# from scripts.python.config import GoogleAPIkey
from scripts.python.GoogleTrends import GT

In [2]:
gt = GT("AIzaSyC3o-2L8wOh8CFbf-zCKdaYrT7yhKe8HFc")

In [10]:
gt.get_graph("CORRUPTION", restrictions_geo="SB")

{'lines': [{'term': 'CORRUPTION',
   'points': [{'value': 0, 'date': '2004-01-01'},
    {'value': 0, 'date': '2004-02-01'},
    {'value': 0, 'date': '2004-03-01'},
    {'value': 84, 'date': '2004-04-01'},
    {'value': 0, 'date': '2004-05-01'},
    {'value': 100, 'date': '2004-06-01'},
    {'value': 0, 'date': '2004-07-01'},
    {'value': 0, 'date': '2004-08-01'},
    {'value': 0, 'date': '2004-09-01'},
    {'value': 0, 'date': '2004-10-01'},
    {'value': 0, 'date': '2004-11-01'},
    {'value': 0, 'date': '2004-12-01'},
    {'value': 0, 'date': '2005-01-01'},
    {'value': 0, 'date': '2005-02-01'},
    {'value': 0, 'date': '2005-03-01'},
    {'value': 0, 'date': '2005-04-01'},
    {'value': 0, 'date': '2005-05-01'},
    {'value': 0, 'date': '2005-06-01'},
    {'value': 0, 'date': '2005-07-01'},
    {'value': 28, 'date': '2005-08-01'},
    {'value': 0, 'date': '2005-09-01'},
    {'value': 44, 'date': '2005-10-01'},
    {'value': 0, 'date': '2005-11-01'},
    {'value': 52, 'date': '2005-12-01'},
    {'value': 0, 'date': '2006-01-01'},
    {'value': 0, 'date': '2006-02-01'},
    {'value': 0, 'date': '2006-03-01'},
    {'value': 0, 'date': '2006-04-01'},
    {'value': 0, 'date': '2006-05-01'},
    {'value': 0, 'date': '2006-06-01'},
    {'value': 0, 'date': '2006-07-01'},
    {'value': 0, 'date': '2006-08-01'},
    {'value': 0, 'date': '2006-09-01'},
    {'value': 0, 'date': '2006-10-01'},
    {'value': 0, 'date': '2006-11-01'},
    {'value': 0, 'date': '2006-12-01'},
    {'value': 0, 'date': '2007-01-01'},
    {'value': 0, 'date': '2007-02-01'},
    {'value': 0, 'date': '2007-03-01'},
    {'value': 11, 'date': '2007-04-01'},
    {'value': 0, 'date': '2007-05-01'},
    {'value': 6, 'date': '2007-06-01'},
    {'value': 0, 'date': '2007-07-01'},
    {'value': 0, 'date': '2007-08-01'},
    {'value': 0, 'date': '2007-09-01'},
    {'value': 10, 'date': '2007-10-01'},
    {'value': 0, 'date': '2007-11-01'},
    {'value': 8, 'date': '2007-12-01'},
    {'value': 0, 'date': '2008-01-01'},
    {'value': 0, 'date': '2008-02-01'},
    {'value': 0, 'date': '2008-03-01'},
    {'value': 0, 'date': '2008-04-01'},
    {'value': 8, 'date': '2008-05-01'},
    {'value': 0, 'date': '2008-06-01'},
    {'value': 0, 'date': '2008-07-01'},
    {'value': 0, 'date': '2008-08-01'},
    {'value': 0, 'date': '2008-09-01'},
    {'value': 0, 'date': '2008-10-01'},
    {'value': 4, 'date': '2008-11-01'},
    {'value': 0, 'date': '2008-12-01'},
    {'value': 0, 'date': '2009-01-01'},
    {'value': 4, 'date': '2009-02-01'},
    {'value': 4, 'date': '2009-03-01'},
    {'value': 0, 'date': '2009-04-01'},
    {'value': 0, 'date': '2009-05-01'},
    {'value': 0, 'date': '2009-06-01'},
    {'value': 0, 'date': '2009-07-01'},
    {'value': 0, 'date': '2009-08-01'},
    {'value': 0, 'date': '2009-09-01'},
    {'value': 0, 'date': '2009-10-01'},
    {'value': 0, 'date': '2009-11-01'},
    {'value': 0, 'date': '2009-12-01'},
    {'value': 0, 'date': '2010-01-01'},
    {'value': 0, 'date': '2010-02-01'},
    {'value': 0, 'date': '2010-03-01'},
    {'value': 0, 'date': '2010-04-01'},
    {'value': 0, 'date': '2010-05-01'},
    {'value': 0, 'date': '2010-06-01'},
    {'value': 0, 'date': '2010-07-01'},
    {'value': 0, 'date': '2010-08-01'},
    {'value': 0, 'date': '2010-09-01'},
    {'value': 0, 'date': '2010-10-01'},
    {'value': 0, 'date': '2010-11-01'},
    {'value': 0, 'date': '2010-12-01'},
    {'value': 0, 'date': '2011-01-01'},
    {'value': 0, 'date': '2011-02-01'},
    {'value': 2, 'date': '2011-03-01'},
    {'value': 3, 'date': '2011-04-01'},
    {'value': 0, 'date': '2011-05-01'},
    {'value': 12, 'date': '2011-06-01'},
    {'value': 0, 'date': '2011-07-01'},
    {'value': 4, 'date': '2011-08-01'},
    {'value': 4, 'date': '2011-09-01'},
    {'value': 0, 'date': '2011-10-01'},
    {'value': 0, 'date': '2011-11-01'},
    {'value': 0, 'date': '2011-12-01'},
    {'value': 3, 'date': '2012-01-01'},
    {'value': 0, 'date': '2012-02-01'},
    {'value': 0, 'date': '2012-03-01'},
    {'value': 0, 'date': '2012-04-01'},
    {'value': 0, 'date': '2012-05-01'},
    {'value': 0, 'date': '2012-06-01'},
    {'value': 0, 'date': '2012-07-01'},
    {'value': 0, 'date': '2012-08-01'},
    {'value': 1, 'date': '2012-09-01'},
    {'value': 0, 'date': '2012-10-01'},
    {'value': 0, 'date': '2012-11-01'},
    {'value': 0, 'date': '2012-12-01'},
    {'value': 4, 'date': '2013-01-01'},
    {'value': 2, 'date': '2013-02-01'},
    {'value': 0, 'date': '2013-03-01'},
    {'value': 0, 'date': '2013-04-01'},
    {'value': 0, 'date': '2013-05-01'},
    {'value': 0, 'date': '2013-06-01'},
    {'value': 0, 'date': '2013-07-01'},
    {'value': 0, 'date': '2013-08-01'},
    {'value': 0, 'date': '2013-09-01'},
    {'value': 0, 'date': '2013-10-01'},
    {'value': 0, 'date': '2013-11-01'},
    {'value': 2, 'date': '2013-12-01'},
    {'value': 0, 'date': '2014-01-01'},
    {'value': 0, 'date': '2014-02-01'},
    {'value': 0, 'date': '2014-03-01'},
    {'value': 0, 'date': '2014-04-01'},
    {'value': 0, 'date': '2014-05-01'},
    {'value': 0, 'date': '2014-06-01'},
    {'value': 0, 'date': '2014-07-01'},
    {'value': 0, 'date': '2014-08-01'},
    {'value': 2, 'date': '2014-09-01'},
    {'value': 0, 'date': '2014-10-01'},
    {'value': 0, 'date': '2014-11-01'},
    {'value': 0, 'date': '2014-12-01'},
    {'value': 0, 'date': '2015-01-01'},
    {'value': 0, 'date': '2015-02-01'},
    {'value': 0, 'date': '2015-03-01'},
    {'value': 0, 'date': '2015-04-01'},
    {'value': 0, 'date': '2015-05-01'},
    {'value': 1, 'date': '2015-06-01'},
    {'value': 0, 'date': '2015-07-01'},
    {'value': 0, 'date': '2015-08-01'},
    {'value': 0, 'date': '2015-09-01'},
    {'value': 0, 'date': '2015-10-01'},
    {'value': 1, 'date': '2015-11-01'},
    {'value': 0, 'date': '2015-12-01'},
    {'value': 1, 'date': '2016-01-01'},
    {'value': 0, 'date': '2016-02-01'},
    {'value': 1, 'date': '2016-03-01'},
    {'value': 0, 'date': '2016-04-01'},
    {'value': 0, 'date': '2016-05-01'},
    {'value': 0, 'date': '2016-06-01'},
    {'value': 0, 'date': '2016-07-01'},
    {'value': 0, 'date': '2016-08-01'},
    {'value': 0, 'date': '2016-09-01'},
    {'value': 0, 'date': '2016-10-01'},
    {'value': 0, 'date': '2016-11-01'},
    {'value': 0, 'date': '2016-12-01'},
    {'value': 0, 'date': '2017-01-01'},
    {'value': 0, 'date': '2017-02-01'},
    {'value': 0, 'date': '2017-03-01'},
    {'value': 0, 'date': '2017-04-01'},
    {'value': 0, 'date': '2017-05-01'},
    {'value': 0, 'date': '2017-06-01'},
    {'value': 1, 'date': '2017-07-01'},
    {'value': 0, 'date': '2017-08-01'},
    {'value': 0, 'date': '2017-09-01'},
    {'value': 0, 'date': '2017-10-01'},
    {'value': 0, 'date': '2017-11-01'},
    {'value': 0, 'date': '2017-12-01'},
    {'value': 0, 'date': '2018-01-01'},
    {'value': 0, 'date': '2018-02-01'},
    {'value': 0, 'date': '2018-03-01'},
    {'value': 0, 'date': '2018-04-01'},
    {'value': 1, 'date': '2018-05-01'},
    {'value': 0, 'date': '2018-06-01'},
    {'value': 0, 'date': '2018-07-01'},
    {'value': 1, 'date': '2018-08-01'},
    {'value': 0, 'date': '2018-09-01'},
    {'value': 0, 'date': '2018-10-01'},
    {'value': 0, 'date': '2018-11-01'},
    {'value': 1, 'date': '2018-12-01'},
    {'value': 0, 'date': '2019-01-01'},
    {'value': 0, 'date': '2019-02-01'},
    {'value': 1, 'date': '2019-03-01'},
    {'value': 1, 'date': '2019-04-01'},
    {'value': 0, 'date': '2019-05-01'},
    {'value': 0, 'date': '2019-06-01'},
    {'value': 0, 'date': '2019-07-01'},
    {'value': 0, 'date': '2019-08-01'},
    {'value': 1, 'date': '2019-09-01'},
    {'value': 1, 'date': '2019-10-01'},
    {'value': 0, 'date': '2019-11-01'},
    {'value': 0, 'date': '2019-12-01'},
    {'value': 1, 'date': '2020-01-01'},
    {'value': 0, 'date': '2020-02-01'},
    {'value': 0, 'date': '2020-03-01'},
    {'value': 0, 'date': '2020-04-01'},
    {'value': 0, 'date': '2020-05-01'},
    {'value': 1, 'date': '2020-06-01'},
    {'value': 0, 'date': '2020-07-01'},
    {'value': 1, 'date': '2020-08-01'},
    {'value': 1, 'date': '2020-09-01'},
    {'value': 0, 'date': '2020-10-01'},
    {'value': 1, 'date': '2020-11-01'},
    {'value': 0, 'date': '2020-12-01'},
    {'value': 0, 'date': '2021-01-01'},
    {'value': 0, 'date': '2021-02-01'},
    {'value': 0, 'date': '2021-03-01'},
    {'value': 0, 'date': '2021-04-01'},
    {'value': 0, 'date': '2021-05-01'},
    {'value': 0, 'date': '2021-06-01'},
    {'value': 1, 'date': '2021-07-01'},
    {'value': 1, 'date': '2021-08-01'},
    {'value': 0, 'date': '2021-09-01'},
    {'value': 1, 'date': '2021-10-01'},
    {'value': 0, 'date': '2021-11-01'},
    {'value': 0, 'date': '2021-12-01'},
    {'value': 0, 'date': '2022-01-01'},
    {'value': 0, 'date': '2022-02-01'},
    {'value': 0, 'date': '2022-03-01'},
    {'value': 0, 'date': '2022-04-01'},
    {'value': 1, 'date': '2022-05-01'},
    {'value': 0, 'date': '2022-06-01'},
    {'value': 0, 'date': '2022-07-01'},
    {'value': 1, 'date': '2022-08-01'},
    {'value': 1, 'date': '2022-09-01'},
    {'value': 0, 'date': '2022-10-01'},
    {'value': 0, 'date': '2022-11-01'},
    {'value': 0, 'date': '2022-12-01'},
    {'value': 0, 'date': '2023-01-01'},
    {'value': 1, 'date': '2023-02-01'}]}]}

## Case-sensitive testing

In [3]:
upper_parms = {
    'terms': "Papua New Guinea",
    'restrictions_geo': "AU",
    'restrictions_startDate': "2004-01"
}

# change terms to lower case
lower_parms = upper_parms.copy()
lower_parms["terms"] = lower_parms["terms"].lower()

upper = gt.get_graph(upper_parms["terms"], upper_parms["restrictions_geo"])
lower = gt.get_graph(lower_parms["terms"], lower_parms["restrictions_geo"])

# test whether keyword is case-sensitive
assert upper["lines"][0]["points"] == lower["lines"][0]["points"], "Keyword is sensitive."

In [4]:
# Transform to df
kw_png = gt.to_df(upper)
kw_png.head(5)

   value       date              term
0     44 2004-01-01  Papua New Guinea
1     91 2004-02-01  Papua New Guinea
2     68 2004-03-01  Papua New Guinea
3     56 2004-04-01  Papua New Guinea
4     63 2004-05-01  Papua New Guinea

## Downloading files

In [5]:
countries = ["fiji", "vanuatu", "palau", "tonga", "samoa", "solomon islands"]
secondary = ["travel", "hotel", "flights"]
geos = ["AU", "NZ", "US", "JP", "HK", "NC"]

for country in countries:

    filename = os.getcwd() + "/data/tourism/trends/trends_" + \
        str(country).replace(" ", "_") + ".csv"

    df = pd.DataFrame()
    df["date"] = pd.date_range(
        start="2004-01-01", end="2022-10-01", freq="MS")

    for geo in geos:
        search_term = [str(country) + " " + str(i) for i in secondary]
        graph_response = gt.get_graph(search_term, restrictions_geo=geo)
        trend_response = gt.get_health_trends(search_term)

        try:
            graph, trend = gt.to_df(graph_response), gt.to_df(trend_response)
            graph["term"] = graph["term"] + "-" + geo
            graph = pd.pivot(graph, index='date',
                             columns='term', values='value')
            df = pd.merge(df, graph, how="left", on="date")

        except:
            print(f"{country}, {search_term} raises an Error.")

    trend = pd.pivot(trend, index='date',
                     columns='term', values='value')
    df = pd.merge(df, trend, how="left", on="date")
    
    df.to_csv(filename, encoding="utf-8")

In [16]:
from bokeh.plotting import figure, show, output_file
from bokeh.models import ColumnDataSource, Legend
from bokeh.palettes import Category20

# output_file('fiji_month_by_country.html')
p = figure(height=600, width=1000,
           title="Google Trend Index By Month",
           x_axis_type="datetime",
           x_axis_label="Date",
           y_axis_label="Google Trend Index",
           tooltips=[("Date", "$Date"),
                     ("Search Index", "@$col")])

cols = df.columns[-3:].tolist()
p.add_layout(Legend(), 'right')
source = ColumnDataSource(df)

for col, color in zip(cols, Category20[3]):
    # have to use different colnames for y-coords so tooltip can refer to @$name
    p.line('date', col, source=df, name=col, legend_label=col, color=color)

p.legend.label_text_font_size = '9pt'
p.legend.click_policy = "mute"
p.legend.location = "top_left"

show(p)